# Generated by Django 3.2.5 on 2022-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(max_length=100)),
                ('cid', models.IntegerField()),
                ('ticker', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('quarter', models.IntegerField()),
                ('year', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('exchange', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=100)),
                ('marketcap', models.FloatField()),
            ],
        ),
    ]
